### ISSUE TITLE
Replace all the project logo icons and the CNCF logo with SVG versions

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/ci-dashboard#77]
**Feature Name:** 

- Replace all the project logo icons and the CNCF logo with SVG versions

**Short Description:** 

- Replace all logos on cncf.ci with SVG versions from https://github.com/cncf/artwork

Projects:
  - K8s
  - CoreDNS
  - Envoy
  - Prometheus
  - Linkerd
  - fluentd
  - ONAP 

Header:
- CNCF 

### Tasks: 

- [x] Update logo for K8s
- [x] Update logo for CoreDNS
- [x] Update logo for Envoy
- [x] Update logo for Prometheus
- [x] Update logo for Linkerd
- [x] Update logo for  fluentd
- [x] Update logo for ONAP

Header:
- [x] Update logo for CNCF 

QA/Promotion:
- [x] Promote to master
  - [x] QA on dev

- [x] Promote to staging
   - [x] QA on staging
 
- [x] Promote to production
   - [x] QA on production

- [x] Close ticket

**Comment by lixuna** [comment]
Update: attempting to add svg logo in the same manner as replacing a png did not work as expected.
- https://github.com/crosscloudci/onap-so-configuration/pull/8

This issue will need planning and prioritizing to support svg file types on cncf.ci 

<img width="517" alt="Screenshot 2019-03-26 16 06 02" src="https://user-images.githubusercontent.com/11701267/55033456-3cee5900-4fe1-11e9-879d-dd72fc0d5525.png">
